# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-default

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: '10.x'
  - task: CmdLine@2
    displayName: 'Install and Build'
    inputs:
      script: 'npm i && npm run build'

  - task: PublishBuildArtifacts@1
    displayName: Publish
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
      ArtifactName: 'drop'
      publishLocation: 'Container'
